### ISSUE TITLE
Deploy to public/private cloud (Amazon EC2, OpenStack) instead of libvirt/kvm

### ISSUE THREAD

**Issue by LenzGr** [SUSE/sesdev#100]
It would be nice if `sesdev` would support deploying a Ceph cluster not only on a local or remote machine running libvirt/qemu, but also "in the Cloud", e.g. on Amazon EC2, OpenStack, Azure, Public-Cloud-Flavor-Of-The-Week, etc. Ideally, I would only have to flip a config switch to use one of these instead of libvirt and provide my Public Cloud access credentials in a config file to switch the deployment mode.

---

UPDATE: this was originally just for Amazon EC2, but since sesdev does not currently support **any** public cloud, I repurposed the ticket to cover them all.

**Comment by LenzGr** [comment]
The most straightforward way is probably using [vagrant-aws](https://github.com/mitchellh/vagrant-aws), but the project seems to have been abandoned/orhphaned a while ago.

Other options to explore: Amazon's [Python SDK for AWS (Boto3)](https://aws.amazon.com/sdk-for-python/) or maybe using [Terraform](https://www.terraform.io/) instead?

**Comment by smithfarm** [comment]
Regarding the use of `boto3`, my also-out-of-date project https://github.com/smithfarm/ceph-auto-aws might provide some useful information, if only from the documentation. FWIW, ceph-auto-aws uses `boto2`, not `boto3`.

**Comment by LenzGr** [comment]
Thanks @smithfarm - I remembered that you had a similar project and was planning on looking into it for inspiration. Thanks for sharing!

**Comment by LenzGr** [comment]
FWIW, I have submitted this issue as a [Hackweek project](https://hackweek.suse.com/19/projects/deploy-a-ceph-cluster-in-aws-using-sesdev) now.

**Comment by toabctl** [comment]
Just for the record - don't try to use vagrant on AWS. it will fail because nested virt does not work. `vagrant-aws` might work but the project doesn't look very active...

**Comment by smithfarm** [comment]
Note: there are two modalities for using sesdev in/with a public cloud:

1. leveraging a yet-to-be-implemented feature (i.e., the feature this issue is asking for) tell sesdev to deploy a Ceph cluster "in the cloud", i.e. sesdev (running locally) would automate the procedure of creating VMs in the cloud and deploying Ceph on those VMs.
1. deploy a VM in the public cloud and then try to install sesdev on it and "run sesdev in the cloud" - for this, see https://github.com/SUSE/sesdev/issues/339
