### ISSUE TITLE
nautilus: fails on stage.4

### ISSUE THREAD

**Issue by tspmelo** [SUSE/sesdev#294]
I'm using latest `master` and when I run the following command it fails on stage.4:
`sesdev create nautilus --repo https://download.opensuse.org/repositories/filesystems:/ceph:/nautilus:/upstream/openSUSE_Leap_15.1/ n`

logs: [sesdev.log](https://github.com/SUSE/sesdev/files/4552356/sesdev.log)

I was able to get it running when using --single-node with the same repo.
It also works if I don't define a repo, so I'm not sure if this is a problem in sesdev or the repo package.

**Comment by smithfarm** [comment]
I'm pretty sure it will work if you omit the `--repo` parameter.

I have never tried to deploy an unpatched upstream nautilus build using DeepSea. I'm not that surprised that it failed. I will make a "real" 14.2.9 SES6 testing build in https://build.opensuse.org/project/show/filesystems:ceph:nautilus:testing

**Comment by smithfarm** [comment]
The failure is:

    add users: Module function rgw.add_users threw an exception.
    Exception: Expecting value: line 1 column 1 (char 0)

**Comment by smithfarm** [comment]
Post Mortem

Stage 4 calls the "rgw.py" module, function "add_users". This is a Salt module. The Salt module runs

    radosgw-admin user list --rgw-realm=default

The first thing radosgw-admin notices is there is no RGW deployed in the cluster, so it starts creating the RGW pools (about 5 of them). In the default sesdev 4-node cluster environment (3 OSD nodes with 2 OSDs each), there is only six OSDs and the `mon_max_pg_per_osd` setting (which defaults to 250) is exceeded. Instead of printing an error in this case, `radosgw-admin` segfaults.
