### ISSUE TITLE
Don't explicitly install  `supportutils-plugin-ses`

### ISSUE THREAD

**Issue by LenzGr** [SUSE/sesdev#524]
After https://github.com/ceph/ceph-salt/pull/383/ has been merged, there is probably no need to explicitly install `supportutils-plugin-ses` via `seslib/templates/zypper.j2` anymore?

See [BSC#1177432](https://bugzilla.suse.com/show_bug.cgi?id=1177432) for details.

**Comment by tserong** [comment]
Actually, sesdev may still need to do this. The problem is that the vagrant box sesdev uses for SLE 15 SP2 has "solver.onlyRequires = true" set in /etc/zypp/zypp.conf (see line 51 of https://build.suse.de/package/view_file/Virtualization:Vagrant:SLE-15-SP2/SLES-15-SP2-Vagrant/config.sh?expand=1), which means the "Supplements: ceph-common" magic from supportutils-plusin-ses.spec will be ignored in that environment.

**Comment by smithfarm** [comment]
I would prefer to install it explicitly. sesdev has many deployment versions, not just ses7, and there is a subcommand called `sesdev supportconfig` which relies on these packages "just being there".

**Comment by smithfarm** [comment]
Actually, I thought of a way to implement this without sacrificing much. And, in the interests of more faithfully simulating a customer environment, it seems like a desirable.

One consequence will be that `supportutils*` will not be installed automagically on client nodes. But that's the case in our products as well.
