### ISSUE TITLE
caasp4 deployment broken

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#567]
`sesdev create caasp4` is currently broken. The spot where it fails is:

```
    master: ++ helm install --namespace metallb-system --name metallb stable/metallb -f /tmp/metallb.yaml
    master: Error: failed to download "stable/metallb" (hint: running `helm repo update` may help)
```

**Comment by colder-is-better** [comment]
The culprit of that particular failure is a "rogue" line in `/etc/hosts` on the Master node (and on any of the Worker nodes):

```
127.0.1.1 master.mycaasp4.test master
```

Such a line prevents `skuba` from properly bootstrapping the cluster. One workaround is to have that line "weeded out" early on, e.g., like this:

```
diff --git a/seslib/templates/provision.sh.j2 b/seslib/templates/provision.sh.j2
index 25251c7..515e418 100644
--- a/seslib/templates/provision.sh.j2
+++ b/seslib/templates/provision.sh.j2
@@ -21,6 +21,7 @@ ls -lR /home/vagrant
 # populate /etc/hosts
 {% for _node in nodes %}
 {% if _node.public_address %}
+sed -ie "/127.0.1.1/d" /etc/hosts
 echo "{{ _node.public_address }} {{ _node.fqdn }} {{ _node.name }}" >> /etc/hosts
 {% endif %}
 {% endfor %}
```

I have tried this workaround and it works, and I am now investigating for the root cause of this issue.

**Comment by smithfarm** [comment]
It's probably vagrant itself that is introducing this line. We used to remove it, but doing so breaks sesdev for folks who use the `--libvirt-networks` option, so we stopped removing it in https://github.com/SUSE/sesdev/pull/199

**Comment by colder-is-better** [comment]
Yup, I also believe this is Vagrant's doing :/ How about we weed out that "rogue" line **only** when deploying a CaaSP cluster?

```
diff --git a/seslib/templates/caasp/master.sh.j2 b/seslib/templates/caasp/master.sh.j2
index c3f2b7a..2790978 100644
--- a/seslib/templates/caasp/master.sh.j2
+++ b/seslib/templates/caasp/master.sh.j2
@@ -3,6 +3,8 @@ zypper --non-interactive install --type pattern SUSE-CaaSP-Management
 
 {% if node.name == 'master' %}
 
+sed -ie "/127.0.1.1/d" /etc/hosts
+
 function wait_for_master_ready {
     set +ex
     echo "Waiting for master to be ready"
```

That way deploying a SES cluster with the `--libvirt-network` option would still work, and we would be able to deploy CaaSP also.

**Comment by smithfarm** [comment]
@colder-is-better 

Good idea! I think `seslib/templates/caasp/master.sh.j2` is the right place for this fix.

Instead of `sed -ie "/127.0.1.1/d" /etc/hosts`, though, would you mind using the original code?

```
# remove the first line introduced by vagrant
head -1 /etc/hosts | grep -q '127.*' && sed -i '1d' /etc/hosts
```

@jan--f JFYI

@colder-is-better I guess we don't have a true root cause analysis, here, right? We just know that removing the `/etc/hosts` line fixes the issue, as long as the `--libvirt-network` option is not given.

**Comment by colder-is-better** [comment]
Well, it's definitely Vagrant's doing, and a _somewhat_ complete root cause analysis would be the following.

When we have a **simple** `Vagrantfile` like this...

```
Vagrant.configure("2") do |config|
  config.vm.box = "sles-15-sp2"
  config.vm.box_check_update = false
  config.vm.synced_folder "./", "/vagrant", disabled: true
end
```

...and we go ahead and `vagrant up`, the `/etc/hosts` file in the resulting box looks like this:

```
[...]

127.0.0.1	localhost

# special IPv6 addresses
::1             localhost ipv6-localhost ipv6-loopback

fe00::0         ipv6-localnet

ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts
```

The so called "rogue" line is not there. It willingly appears, though, as soon as we try to configure networking for our box. Say, for example, we have this slightly more elaborate `Vagrantfile`...

```
Vagrant.configure("2") do |config|
  config.vm.box = "sles-15-sp2"
  config.vm.box_check_update = false
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.define :testbox do |tb|
    tb.vm.hostname = "testbox.local.is"
    tb.vm.network :private_network,
      :ip => "10.20.30.40"
  end
end
```

...and then we go ahead and `vagrant up`. Now, the `/etc/hosts` file in the resulting box looks like this:

```
[...]
127.0.0.1	localhost

# special IPv6 addresses
::1             localhost ipv6-localhost ipv6-loopback

fe00::0         ipv6-localnet

ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts

127.0.1.1 testbox.local.is testbox
```

Notice the very last line, which can cause issues like the one at hand. 

P.S. I certainly don't mind using the original code for removing the problematic line. It's just that, when this code is executed via `seslib/templates/caasp/master.sh.j2`, it has no effect on `/etc/hosts` (more lines are already added **after** the one we want to remove).

**Comment by smithfarm** [comment]
Ah, nevermind. `head -1 /etc/hosts | grep -q '127.*' && sed -i '1d' /etc/hosts` only does something (remove the first line from the file) if the first line starts with `127.` 

Now Vagrant is doing something different, i.e. appending a `127...` line to the *end* of the file, whereas before it was prepending it at the beginning of the file.

<thinking_out_loud>
Maybe there is an option we could send to Vagrant to prevent it from adding this line in the first place? I'm not really excited about "letting Vagrant add a wrong line and then removing it" but if that's the only way...
</thinking_out_loud>

**Comment by colder-is-better** [comment]
Turns out there have already been many complaints about this "feature" of Vagrant ([Vagrant manipulating localhost entry in /etc/hosts #7263](https://github.com/hashicorp/vagrant/issues/7263)).

After reading (a bit diagonally) the discussion above, I discovered that the culprit is this line --> `node.vm.hostname = ...` <-- in the `Vagrantfile`.

So I restored the original `seslib/templates/caasp/master.sh.j2` (no after-the-fact weeding out of the `127.0.1.1`-line from `/etc/hosts`), and introduced this change:

```
diff --git a/seslib/templates/engine/libvirt/vagrant.node.j2 b/seslib/templates/engine/libvirt/vagrant.node.j2
index 87de22b..954eda2 100644
--- a/seslib/templates/engine/libvirt/vagrant.node.j2
+++ b/seslib/templates/engine/libvirt/vagrant.node.j2
@@ -1,7 +1,5 @@
     {{ node.networks }}
 
-    node.vm.hostname = "{{ node.fqdn }}"
-
     node.vm.provider "libvirt" do |lv|
       lv.memory = {{ node.ram }}
       lv.cpus = {{ node.cpus }}
```

Then I went on and tried some deployments, and everything seemed to be working as expected :)

**Comment by smithfarm** [comment]
@colder-is-better Cool. Can you get that patch up in a PR? Then we could ask @jan--f to test it in his environment.
