### ISSUE TITLE
I can no longer deploy a SES7p environment

### ISSUE THREAD

**Issue by s0nea** [SUSE/sesdev#672]
If I do `sesdev create ses7p --single-node ses7p-mini`, it's resulting in:

```
master: Failure in minion: master.ses7p-mini.test
    master: __id__: install cephadm
    master: __run_num__: 72
    master: __sls__: ceph-salt.apply.cephtools
    master: changes: {}
    master: comment: "An error was encountered while installing package(s): Zypper command failure:\
    master:   \ Running scope as unit: run-re1b27466ef274ec3956bcb42a502d618.scopeLoading repository\
    master:   \ data...\nReading installed packages...\nResolving package dependencies...\n\n\
    master:   Problem: the to be installed ceph-base-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64\
    master:   \ requires 'ceph-common = 16.2.9.536+g41a9f9a5573-150300.3.3.1', but this requirement\
    master:   \ cannot be provided\n  not installable providers: ceph-common-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64[storage-update]\n\
    master:   \ Solution 1: do not install ceph-common-16.2.9.536+g41a9f9a5573-150300.6.3.1.x86_64\n\
    master:   \ Solution 2: do not install ceph-base-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64\n\
    master:   \ Solution 3: break ceph-base-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64 by ignoring\
    master:   \ some of its dependencies\n\nChoose from above solutions by number or cancel [1/2/3/c/d/?]\
    master:   \ (c): c"
    master: duration: 725.412
    master: name: install cephadm
    master: result: false
    master: start_time: '10:05:03.261770'
    master: state: pkg_|-install cephadm_|-install cephadm_|-installed
```

**Comment by tserong** [comment]
This is happening because of an unfortunate set of circumstances:

1) There's currently a slight version discrepancy between the ceph-common package present in the SLE 15 SP3 Basesystem vs. SES 7.1 Updates repositories. SP3 Updates has ceph-common-16.2.9.536+g41a9f9a5573-150300.6.3.1, whiles SES 7.1 Updates has ceph-common-16.2.9.536+g41a9f9a5573-150300.3.3.1 (note: 6.3.1 vs. 3.3.1 at the end - it's exactly the same code, just a different build or release number generated by the SUSE build service).
2) `ceph-salt apply` wants to install both ceph-base and ceph-common (https://github.com/ceph/ceph-salt/blob/500b4f3695881958cbb00a3e0f6079b8e031a95c/ceph-salt-formula/salt/ceph-salt/apply/cephtools.sls#L9-L14). ceph-base is only available in SES 7.1 Updates, and is the 3.3.1 version. ceph-common is available in both SES 7.1 Updates (which has the 3.3.1 version) and SP3 Updates (which has the 6.3.1 version).
3) When ceph-salt asks zypper to install both ceph-base and ceph-common, zypper tries to install the newest version of both these packages at the same time, which can't work, because ceph-base explicit requires ceph-common of the exact same version as ceph-base.

Annoyingly, this whole thing could have been avoided if ceph-salt simply only tried to install ceph-base, i.e. this would fix it:

``` diff -u cephtools.sls.orig cephtools.sls
--- cephtools.sls.orig	2022-04-22 10:59:12.000000000 +0200
+++ cephtools.sls	2022-12-16 08:29:13.251355392 +0100
@@ -10,7 +10,6 @@
   pkg.installed:
     - pkgs:
         - ceph-base
-        - ceph-common
     - failhard: True
 
 {{ macros.end_step('Install ceph packages') }}
```
